name: Relikon SEO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74367
title: SEO consulting and developement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0142ff'
    - '#515151'
    - '#0016b3'
    - '#3f85ff'
  brandStrength: 0.8125
  lightness: 0.08677333104424179
  saturation: 0.6427792203612626
  rhythmicContrast: 0.5
purpose: []
