name: Relikon SEO
favicon: null
layout_spectrum: 0.97162
typography_spectrum: 0.25833
title: SEO consulting and developement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0040ff'
    - '#858585'
    - '#00ffff'
    - '#ff00ff'
    - '#ffc000'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
