name: Relikon SEO
favicon: null
layout_spectrum: 0.07912402739748359
typography_spectrum: 0.9139168621040881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8978838541079313
  lightness: 0.08677333104424179
  saturation: 0.6427792203612626
  rhythmicContrast: 0.4789788331836462
purpose: []
