name: Relikon SEO
favicon: null
layout_spectrum: 0.7456
typography_spectrum: 0.49709
title: SEO consulting and developement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0040ff'
    - '#858585'
    - '#00ffff'
    - '#ff00ff'
    - '#ffc000'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
